
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: ".env.local" });
config(); // fallback to .env
import { defineConfig } from "prisma/config";

const fallbackDatabaseUrl =
  "postgresql://placeholder:placeholder@localhost:5432/placeholder";

const databaseUrl = process.env.DATABASE_URL ?? fallbackDatabaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Allow Docker image builds to generate Prisma Client before runtime env vars exist.
    url: databaseUrl,
  },
});
